import React from "react";
import {
    SiJavascript,
    SiTypescript,
    SiPython,
    SiMysql,
    SiReact,
    SiNextdotjs,
    SiRedux,
    SiTailwindcss,
    SiHtml5,
    SiCss3,
    SiFigma,
    SiNodedotjs,
    SiExpress,
    SiSpringboot,
    SiPostgresql,
    SiPrisma,
    SiAmazon,
    SiDocker,
    SiGit,
    SiLinux,
    SiSanity,
    SiExpo,
    SiOpencv,
    SiFlask,
    SiMongodb,
    SiWordpress,
    SiGooglecloud,
    SiApachespark,
    SiScala,
} from "react-icons/si";
import { FaJava, FaDatabase, FaCloud, FaAccessibleIcon } from "react-icons/fa";
import { VscCode } from "react-icons/vsc";
import { TbBrandSocketIo } from "react-icons/tb";

const iconMap: Record<string, React.ReactNode> = {
    JavaScript: <SiJavascript />,
    TypeScript: <SiTypescript />,
    Python: <SiPython />,
    Java: <FaJava />,
    SQL: <SiMysql />,
    React: <SiReact />,
    "React Native": <SiReact />,
    "Next.js": <SiNextdotjs />,
    Redux: <SiRedux />,
    Tailwind: <SiTailwindcss />,
    HTML5: <SiHtml5 />,
    CSS3: <SiCss3 />,
    Figma: <SiFigma />,
    "WCAG 2.0": <FaAccessibleIcon />,
    "Node.js": <SiNodedotjs />,
    Express: <SiExpress />,
    "Spring Boot": <SiSpringboot />,
    PostgreSQL: <SiPostgresql />,
    NeonDB: <FaDatabase />,
    PrismaORM: <SiPrisma />,
    "RESTful APIs": <FaCloud />,
    "MVC Pattern": <VscCode />,
    "AWS (EC2, S3, RDS)": <SiAmazon />,
    AWS: <SiAmazon />,
    "AWS EC2": <SiAmazon />,
    "AWS RDS": <SiAmazon />,
    Docker: <SiDocker />,
    Git: <SiGit />,
    "CI/CD": <FaCloud />,
    "Sanity Studio": <SiSanity />,
    "Unit Testing": <VscCode />,
    Agile: <VscCode />,
    Linux: <SiLinux />,
    Expo: <SiExpo />,
    WebSockets: <TbBrandSocketIo />,
    "deck.gl": <FaCloud />, // No specific icon
    Scala: <SiScala />,
    "Apache Sedona": <SiApachespark />, // Close enough
    ArcGIS: <FaCloud />,
    "Spark SQL": <SiApachespark />,
    Finagle: <VscCode />,
    "Graph API": <FaCloud />,
    ngrok: <FaCloud />,
    OpenPose: <SiOpencv />, // Computer Vision
    "Computer Vision": <SiOpencv />,
    Flask: <SiFlask />,
    MongoDB: <SiMongodb />,
    WordPress: <SiWordpress />,
    GCP: <SiGooglecloud />,
    FastAPI: <SiPython />, // Python framework
    Jest: <VscCode />,
    Maven: <VscCode />,
};

export const getTechIcon = (tech: string) => {
    return iconMap[tech] || <VscCode />;
};
